
package net.ddp2p.common.WSupdate;

import java.net.MalformedURLException;
import java.net.URL;
import javax.xml.namespace.QName;
import javax.xml.ws.Service;
import javax.xml.ws.WebEndpoint;
import javax.xml.ws.WebServiceClient;
import javax.xml.ws.WebServiceException;
import javax.xml.ws.WebServiceFeature;


/**
 * This class was generated by the JAX-WS RI.
 * JAX-WS RI 2.2.4-b01
 * Generated source version: 2.2
 * 
 */
@WebServiceClient(name = "ddWS", targetNamespace = "urn:ddWS", wsdlLocation = "http://localhost:6060/ddWS_doc5.php?wsdl")
public class DdWS
    extends Service
{

    private final static URL DDWS_WSDL_LOCATION;
    private final static WebServiceException DDWS_EXCEPTION;
    private final static QName DDWS_QNAME = new QName("urn:ddWS", "ddWS");

    static {
        URL url = null;
        WebServiceException e = null;
        try {
            url = new URL("http://localhost:6060/ddWS_doc5.php?wsdl");
        } catch (MalformedURLException ex) {
            e = new WebServiceException(ex);
        }
        DDWS_WSDL_LOCATION = url;
        DDWS_EXCEPTION = e;
    }

    public DdWS() {
        super(__getWsdlLocation(), DDWS_QNAME);
    }

    public DdWS(URL wsdlLocation) {
        super(wsdlLocation, DDWS_QNAME);
    }
/*
    // TODO
    public DdWS(WebServiceFeature... features) {
        super(__getWsdlLocation(), DDWS_QNAME, features);
    }
    
    public DdWS(URL wsdlLocation, WebServiceFeature... features) {
        super(wsdlLocation, DDWS_QNAME, features);
    }

    public DdWS(URL wsdlLocation, QName serviceName, WebServiceFeature... features) {
        super(wsdlLocation, serviceName, features);
    }
*/
    public DdWS(URL wsdlLocation, QName serviceName) {
        super(wsdlLocation, serviceName);
    }

    /**
     * 
     * @return
     *     returns DdWSPortType
     */
    @WebEndpoint(name = "ddWSPort")
    public DdWSPortType getDdWSPort() {
        return super.getPort(new QName("urn:ddWS", "ddWSPort"), DdWSPortType.class);
    }

    /**
     * 
     * @param features
     *     A list of {@link javax.xml.ws.WebServiceFeature} to configure on the proxy.  Supported features not in the <code>features</code> parameter will have their default values.
     * @return
     *     returns DdWSPortType
     */
    @WebEndpoint(name = "ddWSPort")
    public DdWSPortType getDdWSPort(WebServiceFeature... features) {
        return super.getPort(new QName("urn:ddWS", "ddWSPort"), DdWSPortType.class, features);
    }

    private static URL __getWsdlLocation() {
        if (DDWS_EXCEPTION!= null) {
            throw DDWS_EXCEPTION;
        }
        return DDWS_WSDL_LOCATION;
    }

}
